### ISSUE TITLE
New map is missing

### ISSUE THREAD

**Issue by O1LER** [SteliosLL/BeamMP-Server-Management-Tool#2]
The new beamNG map Johnson valley is missing in the map list

Its internal shortcut is 

> “/levels/johnson_valley/info.json”

And its preview picture from the menu

![johnson_valley_04_preview](https://user-images.githubusercontent.com/44237025/212131374-7ab13f1a-c152-4160-aa33-41948c218084.jpg)

**Comment by SteliosLL** [comment]
thanks for reminding me. I will add it as soon as i can
