### ISSUE TITLE
Add a Rating and Note System for Maps

### ISSUE THREAD

**Issue by YannD-Deltagon** [SteliosLL/BeamMP-Server-Management-Tool#3]
I would like to suggest the addition of a **rating** and **note** system for maps.

By rating, I mean a star-based system to rate the maps, 
and by notes, I mean written notes to provide some details about the map. 

This would help in better organization and ease of finding maps over time.

**Comment by SteliosLL** [comment]
Sounds like a good idea but i will probably not add this feature since i don't have enough time in my hands. I only add features that are necessary

**Comment by YannD-Deltagon** [comment]
I understand
I just open a .txt with the name of all maps + my note 👯
