### ISSUE TITLE
Add Custom Image Selection for 'Missing' Maps

### ISSUE THREAD

**Issue by YannD-Deltagon** [SteliosLL/BeamMP-Server-Management-Tool#6]
I would like to suggest the addition of a feature to select custom images for maps that are marked as 'missing', even when image files are present. This would enhance the visual representation and management of maps.

**Comment by SteliosLL** [comment]
Hmm im not sure about this. I have to think about it. Seems like too much work for a not so necessary feature

**Comment by YannD-Deltagon** [comment]
I understand, I admit that with 80 maps, I have a little trouble there :D
I will see how the images that your software sees are determined, to retype the ZIPs, I think potentially, the easiest
