### ISSUE TITLE
Inquiry about Development Environment

### ISSUE THREAD

**Issue by YannD-Deltagon** [SteliosLL/BeamMP-Server-Management-Tool#7]
I am interested in contributing to the BeamMP Server Management Tool project and I am a beginner in C#.

I noticed a `.sln` file in the project directory, which suggests that Visual Studio might be used. 
Could you please confirm if Visual Studio is the IDE you are using for this project?

Any additional information about the development environment would be greatly appreciated. Thank you.

**Comment by SteliosLL** [comment]
Yes. I use visual studio. Sorry but i can't work with you. I like coding solo
